<html>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>hola</th>
                    <th>hola</th>
                    <th>hola</th>
                    <th>hola</th>
                    <th>hola</th>
                    <th>hola</th>
                    <th>hola</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                </tr>
                <tr>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                </tr>
                <tr>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                </tr>
                <tr>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                </tr>
                <tr>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                    <td>yei</td>
                </tr>
            </tbody>
        </table>
    </div>
</html>